# Generated by Django 3.1.2 on 2020-10-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField()),
                ('title', models.CharField(max_length=128)),
                ('outline', models.CharField(max_length=512)),
                ('file', models.FileField(upload_to='mdFiles')),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('brief_introduction', models.TextField()),
                ('interests', models.CharField(max_length=128)),
                ('school', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('article_num', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('total_likes', models.IntegerField(default=0)),
                ('articles', models.ManyToManyField(to='blogapp.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('article_num', models.IntegerField(default=0)),
                ('cre_date', models.DateTimeField()),
                ('mod_data', models.DateTimeField()),
                ('brief_introduction', models.TextField()),
                ('total_views', models.IntegerField()),
                ('total_likes', models.IntegerField()),
                ('articles', models.ManyToManyField(to='blogapp.Article')),
            ],
        ),
    ]
