# Generated by Django 3.1.2 on 2020-10-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='article',
            name='name_slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
