# Generated by Django 3.1.2 on 2020-10-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20201019_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='me',
            options={'verbose_name_plural': 'We'},
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
