# Generated by Django 3.1.2 on 2020-10-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20201020_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
