# Generated by Django 3.1.2 on 2020-10-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20201021_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='name_slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='name_slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
