# Generated by Django 3.1.2 on 2020-10-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20201021_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='name_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
