# Generated by Django 3.1.2 on 2020-10-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20201021_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='mod_data',
            new_name='mod_date',
        ),
    ]
