# Generated by Django 3.1.2 on 2020-10-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_auto_20201021_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='brief_introduction',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='brief_introduction',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='me',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='me',
            name='company',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='me',
            name='interests',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='me',
            name='school',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
