# Generated by Django 3.1.2 on 2020-10-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20201022_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='outline',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
