# Generated by Django 3.1.2 on 2020-10-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_auto_20201022_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='brief_introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='brief_introduction',
            field=models.TextField(blank=True),
        ),
    ]
