# Generated by Django 3.1.2 on 2020-10-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_auto_20201022_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
