# Generated by Django 3.1.2 on 2020-10-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_me_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='github',
            field=models.URLField(blank=True),
        ),
    ]
